# Task 1

#ques 1

In [2]:
def divisn(x,y):
    try:
        outpt=x/y
        print("Division Result for your input is:" ,outpt)
        print("Mission Accomplished")
    except ZeroDivisionError:
        print("Invalid input, please attempt again")

a=int(input("Enter first number for divison: "))
b=int(input("Enter second number for divison: "))
divisn(a,b)

Enter first number for divison: 5
Enter second number for divison: 0
Invalid input, please attempt again


#ques 2

In [3]:
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

lst=[(x+' '+n+' '+i) for x in subjects for n in verbs for i in objects]
print('\n'.join(lst))



Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


# Task 2

#ques 1

In [2]:
import numpy as np
def matx(x,n):
    
    print("output matrix is :",np.column_stack([x**(n-1-i) for i in range(n)]))
    
a=np.array((1,2,3,5))
b=int(input("enter number of columns "))
matx(a,b)

enter number of columns 5
output matrix is : [[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [625 125  25   5   1]]
